import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

import apiSidebar from './docs/api/sidebar.js';

const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Self-Hosting',
      items: [
        {
          type: 'autogenerated',
          dirName: 'self-hosting',
        },
      ],
    },
    {
      type: 'category',
      label: 'SDKs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sdks',
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Solutions',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai-solutions',
        },
      ],
    },
    {
      type: 'category',
      label: 'Webhooks',
      items: [
        {
          type: 'autogenerated',
          dirName: 'webhooks',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'generated-index',
        title: 'Plane API',
        description:
          'Learn how to interact with Plane programmatically, including authentication, endpoints, and data structures.',
        slug: '/api',
      },
      items: apiSidebar,
    },
  ],
};

export default sidebars;
